@Kafkaf.API_HostAddress = http://localhost:5175


GET {{Kafkaf.API_HostAddress}}/debug/routes
Accept: application/json

###

GET {{Kafkaf.API_HostAddress}}/api/clusters
Accept: application/json

### 

GET {{Kafkaf.API_HostAddress}}/api/clusters/0
Accept: application/json

### 

GET {{Kafkaf.API_HostAddress}}/api/clusters/configs
Accept: application/json

### 

#
# Brokers
#

GET {{Kafkaf.API_HostAddress}}/api/clusters/0/brokers
Accept: application/json

### 


GET {{Kafkaf.API_HostAddress}}/api/clusters/0/brokers/1
Accept: application/json

### 

GET {{Kafkaf.API_HostAddress}}/api/clusters/0/topics
Accept: application/json

###

GET {{Kafkaf.API_HostAddress}}/api/clusters/0/topics/test.1
Accept: application/json

###
GET {{Kafkaf.API_HostAddress}}/api/clusters/0/topics/test.1/messages?partitions=0,1,2
Accept: application/json

###
GET {{Kafkaf.API_HostAddress}}/api/clusters/0/topics/test.3/messages?partitions=0
Accept: application/json