@Kafkaf.API_HostAddress = http://localhost:5175


GET {{Kafkaf.API_HostAddress}}/debug/routes
Accept: application/json

###

GET {{Kafkaf.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Kafkaf.API_HostAddress}}/api/Clusters
Accept: application/json

### 

GET {{Kafkaf.API_HostAddress}}/api/Clusters/0
Accept: application/json

### 

GET {{Kafkaf.API_HostAddress}}/api/Clusters/Configs
Accept: application/json

### 

#
# Brokers
#
GET {{Kafkaf.API_HostAddress}}/api/Clusters/0/Brokers
Accept: application/json

### 


GET {{Kafkaf.API_HostAddress}}/api/clusters/0/brokers/1
Accept: application/json

### 
